# Generated by Django 3.0.3 on 2020-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Username/E-mail'),
        ),
    ]
