# Generated by Django 3.0.3 on 2020-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200226_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Endereço de email'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Último nome'),
        ),
    ]
