# Generated by Django 3.0.3 on 2020-02-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
